### ISSUE TITLE
bad thing has malware dont download

### ISSUE THREAD

**Issue by macimas** [daniel071/ramDownloader#1]
ramdownloader fake
contain malware
pls no no install

**Comment by daniel071** [comment]
![Proof its no malware](https://user-images.githubusercontent.com/45705145/92304756-34ff5a80-efc4-11ea-8f30-6c8dc81b28b7.png)
It's safe, and you can look at the source code if you think it isn't.

**Comment by macimas** [comment]
it kil computer
