### ISSUE TITLE
my ram didn't downloded

### ISSUE THREAD

**Issue by braainsiogame** [daniel071/ramDownloader#2]
hi it's jeremy from oklahoma i have 4 gb of rams only and this didn't worked imma sue you

**Comment by daniel071** [comment]
CloudRAM 2.0 only works on DDR4 ram, that might be the issue.

**Comment by daniel071** [comment]
Someone has ported CloudRAM 2.0 to DDR3 RAM, [click here for more info](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
